publiccodenet/projects

- index.md
fixes #8 
-----
[View rendered index.md](https://github.com/Ainali/projects/blob/add-govgame/index.md)
> Added governance game to list

- index.md
This is a quick polish of this page to help people who end up here looking for our codebases. This closes #11 (though we could be more ambitious with this page in the future).
-----
[View rendered index.md](https://github.com/publiccodenet/projects/blob/intro-text/index.md)
> Adding context, add link to codebases, polishing project descriptions

- index.md
Closes #13.
-----
[View rendered index.md](https://github.com/publiccodenet/projects/blob/bumperscripter/index.md)
> New intro lines to make the bumperscripter make more sense

- index.md
Fixes #18 
-----
[View rendered index.md](https://github.com/Ainali/projects/blob/ja-add-oasc-course/index.md)
> Add Standard for Public Code introduction course

- index.md
Fixes #19 
-----
[View rendered index.md](https://github.com/Ainali/projects/blob/ja-add-podcast/index.md)
> Add our podcast to the listed projects

- talks-and-articles.md
Fixes #30, #29.
-----
[View rendered talks-and-articles.md](https://github.com/publiccodenet/projects/blob/missing-comms/talks-and-articles.md)
> Add missing talks and authored articles 

- .github/workflows/link-check.yml
- .github/workflows/test.yml
- .travis.yml
- Gemfile
- README.md
- script/check-new-links.sh
- script/cibuild.sh
- script/test-with-link-check.sh
- script/test-without-link-check.sh
-----
[View rendered README.md](https://github.com/publiccodenet/projects/blob/gh-actions-20210309/README.md)
> Prep for GH Actions

- talks-and-articles.md
This article accompanied @nebster's Media Architecture Biennale 2020 panel on [public digital cultural infrastructure](https://mab20.mediaarchitecture.org/events/towards-public-digital-cultural-infrastructure/).
-----
[View rendered talks-and-articles.md](https://github.com/publiccodenet/projects/blob/volume-59/talks-and-articles.md)
> Add @nebster's Volume article for MAB20 to authored articles list

- talks-and-articles.md
Fixes #65
-----
[View rendered talks-and-articles.md](https://github.com/publiccodenet/projects/blob/ja-foss-summit-india-talk/talks-and-articles.md)
> Add talk from Open Source Summit India

- talks-and-articles.md
null
-----
[View rendered talks-and-articles.md](https://github.com/publiccodenet/projects/blob/os2-blog2/talks-and-articles.md)
> Add article on os2 blog

- talks-and-articles.md
Fixes #73
-----
[View rendered talks-and-articles.md](https://github.com/publiccodenet/projects/blob/code-for-all-2021/talks-and-articles.md)
> Add Code for all talk

- index.md
- talks-and-articles.md
Closes #38
-----
[View rendered index.md](https://github.com/publiccodenet/projects/blob/Add-blog-link/index.md)
[View rendered talks-and-articles.md](https://github.com/publiccodenet/projects/blob/Add-blog-link/talks-and-articles.md)
> Add blog link

- articles.md
- index.md
- talks.md
Closes #34.
-----
[View rendered articles.md](https://github.com/publiccodenet/projects/blob/#34/articles.md)
[View rendered index.md](https://github.com/publiccodenet/projects/blob/#34/index.md)
[View rendered talks.md](https://github.com/publiccodenet/projects/blob/#34/talks.md)
> Split talks and articles

- talks.md
Fixes #97
-----
[View rendered talks.md](https://github.com/publiccodenet/projects/blob/fosdem-2022/talks.md)
> Add FOSDEM to list

- index.md
Fixes #103
-----
[View rendered index.md](https://github.com/publiccodenet/projects/blob/community-translation/index.md)
> Add subsection about community translations

- talks.md
Fixes #104
-----
[View rendered talks.md](https://github.com/publiccodenet/projects/blob/ow2con22/talks.md)
> Add OW2con22 talk

- talks.md
null
-----
[View rendered talks.md](https://github.com/publiccodenet/projects/blob/fossasia-2022/talks.md)
> Add talk from FOSSAsia

- _config.yml
- index.md
Co-Authored-By: Jan Ainali <ainali.jan@gmail.com>
-----
[View rendered index.md](https://github.com/ericherman/projects/blob/fix-redir-20220627/index.md)
> Fix redirect_from

- _config.yml
- index.md
- talks.md
Fix redirect
-----
[View rendered index.md](https://github.com/publiccodenet/projects/blob/release-20220627/index.md)
> Release 20220627

- index.md
Fixes #117
-----
[View rendered index.md](https://github.com/publiccodenet/projects/blob/implementation-guide/index.md)
> Add implementation guide

- 404.md
null
-----
[View rendered 404.md](https://github.com/publiccodenet/projects/blob/adds-404/404.md)
> adds custom 404

- talks.md
null
-----
[View rendered talks.md](https://github.com/publiccodenet/projects/blob/opensource-lisbon-2022/talks.md)
> Add Open Source Lisbon talk by Ben

- 404.md
- Gemfile
- index.md
- talks.md
null
-----
[View rendered 404.md](https://github.com/publiccodenet/projects/blob/release-20221122/404.md)
[View rendered index.md](https://github.com/publiccodenet/projects/blob/release-20221122/index.md)
[View rendered talks.md](https://github.com/publiccodenet/projects/blob/release-20221122/talks.md)
> Release 20221122

- index.md
Already implied by it being a game.
> Remove interactive as word for describing the governance game

- articles.md
- talks.md
Seems like good places to have this link.
> Add press link to talks and articles Further reading

- talks.md
> Add MozFest 2023 session to talks

- talks.md
> Add NLUUG talk to list

- index.md
Reverts publiccodenet/projects#156
> Revert "Suggests improvement to introduction"

- index.md
Closes  #4
Or is this too much :sparkles: ? I thought it might be a nice way to get people's attention.
> Proposes call to action for projects page

- index.md
Continue on the work reverted in #159, based on discussion on #156
> Improves introduction

- talks.md
(Our video and about half the others are already up.)
> Add FOSDEM 2024

- talks.md
Slightly different formatting, since there's no public talk description. I'm open to standardizing this format more if you have a model that you think fits better.
> Add OSPOlogy talks

- talks.md
> Release 20240314
